# Generated by Django 4.0.5 on 2022-07-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_book_contributor_review_bookcontributor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='taring',
            new_name='rating',
        ),
    ]
